sudo: required
language: bash

# Only build pushes to master.
branches:
  only:
    - master

services:
  - docker

cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"

env:
  global:
    - DOCKER_VERSION=1.10.1-0~trusty
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  # upgrade docker-engine to specific version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}

  # Install envtpl for easy templating.
  - sudo pip install envtpl

  - mkdir "$HOME/.bintray"
  - envtpl < .nexuscredential > "$HOME/.ivy2/.credentials"
  - envtpl < .credentials > "$HOME/.bintray/.credentials"

  - export CI_BUILD_NUMBER=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $CI_BUILD_NUMBER; else echo "${TRAVIS_BUILD_NUMBER}-SNAPSHOT"; fi)
  - echo "CI_BUILD_NUMBER=${CI_BUILD_NUMBER}"

  # Login to mup.cr
  - docker login --email not@val.id --username travis --password $DOCKER_PASS mup.cr

script:
  - make package
